# -*- coding: utf-8 -*-
"""predicciónValorAuto_metricas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-vqyYWCc2GRRgUqOwgwxE_4v2Gqn1VS

predecir precio automovil segun variables multiples con regresion lineal y metricas

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split #divide datos en conjunto de train y test
from sklearn.linear_model import LinearRegression #modelo de regresion lineal
from sklearn.metrics import mean_squared_error, r2_score #metricas para evaluar el modelo

#simula datos
np.random.seed(10)
anio = np.random.randint(2005, 2023,50)
kilometraje = np.random.randint(20000, 200000,50)
cilindrada = np.random.uniform(1.0, 3.5,50)
precio = 30000 + (anio -2005) * 1000 - (kilometraje / 10) - cilindrada * 5000 + np.random.normal(-5000,5000,50)

data_autos = pd.DataFrame({'año': anio, 'kilometraje': kilometraje, 'cilindrada': cilindrada, 'precio': precio})
data_autos.head(10)

#dividir los datos
X = data_autos[['año', 'kilometraje', 'cilindrada']]
y = data_autos['precio']

#entrenamiento de los datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
#aplicar modelo
modelo = LinearRegression()
modelo.fit(X_train, y_train)#evitar sobreajuste
#prediccion
y_pred = modelo.predict(X_test)
print(y_pred[0])

#aplicar metricas
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) #raiz de mse
r2 = r2_score(y_test, y_pred)
#imprimir
print(f'MSE: {mse}')
print(f'RMSE: {rmse}')#el modelo se equivoca en 5993 dolares en promedio
print(f'R2: {r2}') #variación de 52%
#En conclusión el modelo predictivo tiene muchos errores
#influyen las variables
#relacion no lineal entre variables
#datos no lineales