# -*- coding: utf-8 -*-
"""predicciónNota_metricas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-vqyYWCc2GRRgUqOwgwxE_4v2Gqn1VS

predecir nota final del estudiante con regresion lineal y metricas
---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split #divide datos en conjunto de train y test
from sklearn.linear_model import LinearRegression #modelo de regresion lineal
from sklearn.metrics import mean_squared_error, r2_score #metricas para evaluar el modelo

#datos simulados
np.random.seed(1)
horas_estudio = np.random.randint(1, 10, 30)
nota_final = 20 + horas_estudio * 6 + np.random.randint(-5, 5, 30)
#crear dataframe
df = pd.DataFrame({'horas_estudio': horas_estudio, 'nota_final': nota_final})
df.head(10)

#dividir los datos
X = df[['horas_estudio']]
y = df['nota_final']

#entrenar el modelo, dividir el conjunto en train (70%) y test (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#aplicar modelo de regresion lineal
model = LinearRegression()
model.fit(X_train, y_train) #evitar sobreajuste significa para que no se acostumbre a los mismos datos
y_pred = model.predict(X_test)
y_pred[0]

#validación del modelo
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)#raiz cuadrada de mse
r2 = r2_score(y_test, y_pred)
print('MSE:', mse) # se equivoca en 9 unidades
print('RMSE:', rmse) #error de 3 puntos en la nota final
print('R2:', r2) # 97 % de variación de las notas